apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: elastic-stack
spec:
  version: 8.5.1
  count: 1
  # ECK configure automatiquement l'authentification et le TLS entre les
  # composants référencés.
  elasticsearchRef:
    name: elasticsearch
  # Requis à partir d'APM Server 8 pour l'application APM et la configuration
  # centrale des agents.
  kibanaRef:
    name: es-kb-quickstart-eck-kibana
  config:
    apm-server:
      otlp:
        enabled: true
    http:
      enabled: true
      host: 127.0.0.1
      port: 5066
    monitoring:
      enabled: false
