apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - package-registry.yaml
  - kibana.yaml
  - fleet-server.yaml
  - apm-server.yaml
  - kubernetes-logs-agent.yaml
  - kube-state-metrics.yaml
  - elastic-ingress.yaml
