apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - elasticsearch-resources.yaml
  - kibana.yaml
  - fleet-server.yaml
  - apm-server.yaml
  - otel-collector-infrastructure.yaml
  - otel-collector-gateway.yaml
  - kubernetes-logs-agent.yaml
  - elastic-ingress.yaml
