---
all:
  children:
    supermarket_middleware_nodes:
      hosts:
        supermarket-middleware-01:
          ansible_host: 192.168.33.10
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/supermarket-middleware-01/virtualbox/private_key
          node_ip: 192.168.33.10
    otel_backend_nodes:
      hosts:
        otel-backend-01:
          ansible_host: 192.168.33.20
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/otel-backend-01/virtualbox/private_key
          node_ip: 192.168.33.20
    otel_edge_nodes:
      hosts:
        otel-edge-01:
          ansible_host: 192.168.33.30
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/otel-edge-01/virtualbox/private_key
          node_ip: 192.168.33.30
    elk_nodes:
      hosts:
        elk-01:
          ansible_host: 192.168.33.40
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/elk-01/virtualbox/private_key
          node_ip: 192.168.33.40
    k3s_nodes:
      hosts:
        k3s-01:
          ansible_host: 192.168.33.50
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/k3s-01/virtualbox/private_key
          node_ip: 192.168.33.50
    elastic_agent_nodes:
      children:
        supermarket_middleware_nodes:
        otel_backend_nodes:
        otel_edge_nodes:
        elk_nodes:
