---
all:
  vars:
    ansible_user: vagrant
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  children:
    poc_nodes:
      hosts:
        poc-01:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_ssh_private_key_file: .vagrant/machines/poc-01/virtualbox/private_key
    otel_backend_nodes:
      hosts:
        otel-backend-01:
          ansible_host: 192.168.33.20
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/otel-backend-01/virtualbox/private_key
    edge_nodes:
      hosts:
        edge-01:
          ansible_host: 192.168.33.30
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/edge-01/virtualbox/private_key
    elk_nodes:
      hosts:
        elk-01:
          ansible_host: 192.168.33.40
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/elk-01/virtualbox/private_key
