---
- name: Configurer uniquement l'Elastic Agent EDOT
  hosts: all
  become: true
  gather_facts: true
  vars:
    elastic_agent_version: 9.4.3
    otel_edge_ip: 192.168.33.30
    elk_ip: 192.168.33.40
    postgresql_database: observability_test
    postgresql_user: observability
    postgresql_password: "{{ lookup('env', 'POSTGRESQL_PASSWORD') | default('password', true) }}"
    fleet_enrollment_token: "{{ lookup('env', 'FLEET_ENROLLMENT_TOKEN') | default('', true) }}"

  roles:
    - role: elastic_agent
