---
- name: Provisionner les quatre VM de la plateforme architecture
  hosts: all
  become: true
  gather_facts: true
  vars:
    poc_ip: 192.168.33.10
    otel_backend_ip: 192.168.33.20
    otel_edge_ip: 192.168.33.30
    elk_ip: 192.168.33.40
    postgresql_database: observability_test
    postgresql_user: observability
    postgresql_password: ""
    postgresql_otel_user: otel
    postgresql_otel_password: "{{ postgresql_password }}"
    mongodb_otel_user: otel_monitor
    mongodb_password: ""
    mongodb_otel_password: "{{ mongodb_password }}"
    kafka_cluster_id: q1Sh-9_ISia_zwGINzRvyQ
    kafka_controller_voters: 1@192.168.33.10:9093
    otel_gateway_kafka_broker: 192.168.33.10:9092
    elastic_agent_version: 9.4.3
    apm_server_version: 9.4.3
    elastic_password: ""
    otel_elasticsearch_api_key: ""
    fleet_enrollment_token: ""
    zscaler_ca_cert_content: ""
    fleet_url: "http://{{ elk_ip }}:8220"

  roles:
    - role: common
    - role: retention
    - role: elastic_agent
    - role: poc
      when: node_role == 'poc'
    - role: otel_backend
      when: node_role == 'otel_backend'
    - role: otel_edge
      when: node_role == 'otel_edge'
    - role: elk
      when: node_role == 'elk'
