otel.service.name=inventory-service
otel.service.version=1.0.0
otel.exporter.otlp.endpoint=http://otel-edge-vm.elastic-stack.svc.cluster.local:4318
otel.exporter.otlp.protocol=http/protobuf
otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none
otel.propagators=tracecontext,baggage
