server:
  port: 3000

order-service:
  inventory-service-url: http://inventory-service:3001
  cron: "0 */1 * * * *"

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:192.168.33.10:9092,192.168.33.11:9092,192.168.33.12:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://otel-collector-gateway.elastic-stack.svc:4318/v1/metrics}
        step: 60s
        compression-mode: gzip
