apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: eck-elasticsearch-https
  namespace: elastic-stack-v2
spec:
  rootCAsSecrets:
    - elasticsearch-es-http-certs-public
  serverName: elasticsearch-es-http.elastic-stack-v2.svc
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: eck-kibana-https
  namespace: elastic-stack-v2
spec:
  rootCAsSecrets:
    - es-kb-quickstart-eck-kibana-kb-http-certs-public
  serverName: es-kb-quickstart-eck-kibana-kb-http.elastic-stack-v2.svc
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: eck-fleet-https
  namespace: elastic-stack-v2
spec:
  rootCAsSecrets:
    - fleet-server-agent-http-certs-public
  serverName: fleet-server-agent-http.elastic-stack-v2.svc
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: elasticsearch
  namespace: elastic-stack-v2
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`elasticsearch.poc.test`)
      services:
        - name: elasticsearch-es-http
          port: 9200
          scheme: https
          serversTransport: eck-elasticsearch-https
  tls:
    secretName: elastic-public-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kibana
  namespace: elastic-stack-v2
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`kibana.poc.test`)
      services:
        - name: es-kb-quickstart-eck-kibana-kb-http
          port: 5601
          scheme: https
          serversTransport: eck-kibana-https
  tls:
    secretName: elastic-public-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fleet-server
  namespace: elastic-stack-v2
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`fleet.poc.test`)
      services:
        - name: fleet-server-agent-http
          port: 8220
          scheme: https
          serversTransport: eck-fleet-https
  tls:
    secretName: elastic-public-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: otel-gateway
  namespace: elastic-stack-v2
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`otel-gateway-v2.poc.test`)
      services:
        - name: otel-gateway
          port: 4318
  tls:
    secretName: elastic-public-tls
