apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: h0tl-supermarche-app
commonAnnotations:
  observability.systemlens.io/architecture-version: v3
resources:
  - ../base
images:
  - name: order-service
    newTag: 1.1.3
  - name: inventory-service
    newTag: 1.1.3
  - name: restock-service
    newTag: 1.1.3
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: order-service-otel-config
    files:
      - otel.properties=otel/order-service.properties
  - name: inventory-service-otel-config
    files:
      - otel.properties=otel/inventory-service.properties
  - name: restock-service-otel-config
    files:
      - otel.properties=otel/restock-service.properties
patches:
  - path: data-endpoints.yaml
  - path: otel-instrumentation.yaml
